CREATE TABLE app_user (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(150) NOT NULL UNIQUE,
  email VARCHAR2(254),
  password VARCHAR2(255) NOT NULL,
  first_name VARCHAR2(150),
  last_name VARCHAR2(150),
  role VARCHAR2(20) DEFAULT 'cliente',
  is_active NUMBER(1) DEFAULT 1
);

CREATE TABLE profile (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  phone VARCHAR2(20),
  address VARCHAR2(255),
  CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE category (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  slug VARCHAR2(150) UNIQUE
);

CREATE TABLE game (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id NUMBER,
  name VARCHAR2(200) NOT NULL,
  description CLOB,
  price NUMBER(10,2) DEFAULT 0,
  cover VARCHAR2(512),
  stock NUMBER DEFAULT 0,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_game_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  total NUMBER(10,2),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE order_item (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER,
  game_id NUMBER,
  quantity NUMBER,
  price NUMBER(10,2),
  CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_orderitem_game FOREIGN KEY (game_id) REFERENCES game(id)
);

INSERT INTO category (name, slug) VALUES ('Aventura','aventura');
INSERT INTO game (category_id, name, description, price, cover, stock)
VALUES (1, 'Horizon Zero Dawn', 'Juego de aventura', 39990, '/static/img/horizon.webp', 10);
COMMIT;
