# Generated by Django 5.2.6 on 2025-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPPG', '0003_cliente_producto_remove_persona_comuna_delete_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prueba', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
