# Generated by Django 5.2.6 on 2025-10-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPPG', '0005_categoria_itempedido_pedido_delete_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'db_table': 'myppg_genero',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_top', models.IntegerField(default=5)),
                ('imagen_fondo', models.URLField(blank=True, max_length=500, null=True)),
                ('web_juego', models.URLField(blank=True, max_length=500, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myppg_juego',
                'ordering': ['-rating', 'nombre'],
            },
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='myppg_categoria',
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='myppg_itempedido',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='myppg_pedido',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='myppg_producto',
        ),
        migrations.CreateModel(
            name='GeneroJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPPG.genero')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos_juego', to='myPPG.juego')),
            ],
            options={
                'db_table': 'myppg_generojuego',
                'unique_together': {('juego', 'genero')},
            },
        ),
    ]
